"""
Privacy Policy Generator for MoM Generator.

This module generates privacy policy documentation and compliance reports.
"""

import os
import logging
from typing import Dict, Any, Optional, List
from datetime import datetime

logger = logging.getLogger(__name__)


class PrivacyPolicyGenerator:
    """
    Generator for privacy policy documentation and compliance reports.
    
    This class creates comprehensive privacy policy documentation
    that can be customized for different organizations and jurisdictions.
    """
    
    def __init__(self, config: Dict[str, Any]):
        """
        Initialize the PrivacyPolicyGenerator.
        
        Args:
            config (Dict[str, Any]): Configuration settings
        """
        self.config = config
        self.organization_name = config.get('organization_name', 'Your Organization')
        self.contact_email = config.get('contact_email', 'privacy@yourorganization.com')
        self.jurisdiction = config.get('jurisdiction', 'General')
        
    def generate_privacy_policy(self, output_path: Optional[str] = None) -> str:
        """
        Generate a comprehensive privacy policy document.
        
        Args:
            output_path (str, optional): Path to save the policy document
            
        Returns:
            str: Privacy policy content
        """
        policy_content = self._create_privacy_policy_content()
        
        if output_path:
            try:
                with open(output_path, 'w', encoding='utf-8') as f:
                    f.write(policy_content)
                logger.info(f"Privacy policy saved to: {output_path}")
            except Exception as e:
                logger.error(f"Error saving privacy policy: {e}")
        
        return policy_content
    
    def _create_privacy_policy_content(self) -> str:
        """Create the privacy policy content."""
        return f"""# Privacy Policy for MoM Generator

**Effective Date:** {datetime.now().strftime('%B %d, %Y')}
**Organization:** {self.organization_name}
**Contact:** {self.contact_email}

## 1. Introduction

This Privacy Policy describes how {self.organization_name} ("we," "our," or "us") collects, uses, and protects your information when you use our AI-powered Minutes of Meeting (MoM) Generator application ("the Service").

## 2. Information We Collect

### 2.1 Meeting Transcripts
- **What we collect:** Meeting transcripts, audio recordings, and related meeting content that you upload or provide to the Service.
- **Purpose:** To generate structured meeting minutes and summaries.
- **Retention:** {self.config.get('data_retention_days', 30)} days by default, configurable based on your settings.

### 2.2 Generated Content
- **What we collect:** Meeting minutes, summaries, and other outputs generated by our AI system.
- **Purpose:** To provide you with the requested meeting documentation.
- **Retention:** {self.config.get('data_retention_days', 30)} days by default, or as configured in your settings.

### 2.3 Usage Information
- **What we collect:** Information about how you use the Service, including processing preferences and configuration settings.
- **Purpose:** To improve the Service and provide technical support.

## 3. How We Use Your Information

We use your information for the following purposes:

- **Primary Service Delivery:** Processing meeting transcripts to generate meeting minutes
- **Service Improvement:** Analyzing usage patterns to enhance our AI models and features
- **Technical Support:** Providing assistance and troubleshooting when needed
- **Legal Compliance:** Meeting legal obligations and protecting our rights

## 4. Data Processing Modes

### 4.1 Online Mode
- Data may be processed using cloud-based AI services
- Transcripts are temporarily stored for processing
- Enhanced AI capabilities available

### 4.2 Offline Mode
- All processing occurs locally on your device
- No data is transmitted to external servers
- Limited AI capabilities but maximum privacy

### 4.3 Privacy Mode
- Enhanced data protection measures
- Automatic data anonymization
- Reduced data retention periods

## 5. Data Retention and Deletion

### 5.1 Automatic Deletion
- **Transcripts:** Automatically deleted after {self.config.get('data_retention_days', 30)} days
- **Temporary Files:** Deleted after 24 hours
- **Generated Content:** Retained for {self.config.get('data_retention_days', 30)} days unless otherwise specified

### 5.2 Manual Deletion
- You can delete your data at any time through the application settings
- Secure deletion methods are used to ensure data cannot be recovered
- Deletion requests are processed immediately

### 5.3 Data Categories and Retention
- **Meeting Transcripts:** {self.config.get('retention_categories', {}).get('transcripts', 30)} days
- **Generated Minutes:** {self.config.get('retention_categories', {}).get('mom_outputs', 60)} days
- **System Logs:** {self.config.get('retention_categories', {}).get('logs', 7)} days
- **Cache Files:** {self.config.get('retention_categories', {}).get('cache', 30)} days

## 6. Data Security

We implement appropriate technical and organizational measures to protect your data:

### 6.1 Technical Measures
- **Encryption:** Data is encrypted both in transit and at rest
- **Access Controls:** Strict access controls limit who can access your data
- **Secure Deletion:** Multi-pass secure deletion ensures data cannot be recovered
- **Local Processing:** Option for complete local processing without external data transmission

### 6.2 Organizational Measures
- **Privacy by Design:** Privacy considerations are built into our system architecture
- **Regular Audits:** Regular security and privacy audits
- **Staff Training:** All personnel are trained on data protection requirements

## 7. Your Rights

Depending on your jurisdiction, you may have the following rights:

### 7.1 Access Rights
- **Right to Access:** Request information about what personal data we hold about you
- **Data Portability:** Export your data in a machine-readable format

### 7.2 Control Rights
- **Right to Rectification:** Correct inaccurate personal data
- **Right to Erasure:** Request deletion of your personal data
- **Right to Restrict Processing:** Limit how we process your data

### 7.3 Objection Rights
- **Right to Object:** Object to processing of your personal data
- **Withdrawal of Consent:** Withdraw consent for data processing at any time

## 8. Data Anonymization

When anonymization is enabled:

- **Personal Identifiers:** Names, email addresses, and phone numbers are removed or replaced
- **Meeting Participants:** Speaker names are replaced with generic identifiers
- **Sensitive Information:** Addresses and other sensitive data are redacted
- **Reversibility:** Anonymization is designed to be irreversible

## 9. Third-Party Services

### 9.1 AI Processing Services
- When using online mode, we may use third-party AI services for processing
- These services are bound by strict data processing agreements
- Data is only used for processing your specific requests

### 9.2 Integration Services
- Optional integrations with calendar and task management systems
- You control which integrations are enabled
- Each integration has its own privacy considerations

## 10. International Data Transfers

- **Local Processing:** We prioritize local processing to minimize data transfers
- **Adequate Protection:** When transfers are necessary, we ensure adequate protection measures
- **User Control:** You can restrict processing to local-only mode

## 11. Children's Privacy

Our Service is not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13.

## 12. Changes to This Policy

We may update this Privacy Policy from time to time. We will notify you of any changes by:
- Posting the new Privacy Policy in the application
- Sending you a notification if you have provided contact information
- Updating the "Effective Date" at the top of this policy

## 13. Contact Information

If you have questions about this Privacy Policy or our data practices, please contact us:

- **Email:** {self.contact_email}
- **Organization:** {self.organization_name}

## 14. Compliance Information

This Privacy Policy is designed to comply with:
- General Data Protection Regulation (GDPR)
- California Consumer Privacy Act (CCPA)
- Other applicable privacy laws in your jurisdiction

## 15. Technical Implementation

### 15.1 Data Storage
- **Location:** {self.config.get('data_storage_location', 'Local device')}
- **Encryption:** {self.config.get('encryption_method', 'AES-256')}
- **Backup:** {self.config.get('backup_policy', 'No automatic backups')}

### 15.2 Processing Options
- **Offline Mode Available:** {'Yes' if self.config.get('offline_mode_available', True) else 'No'}
- **Privacy Mode Available:** {'Yes' if self.config.get('privacy_mode_available', True) else 'No'}
- **Data Anonymization:** {'Available' if self.config.get('anonymization_available', True) else 'Not available'}

---

**Last Updated:** {datetime.now().strftime('%B %d, %Y')}
**Version:** 1.0
"""
    
    def generate_data_processing_agreement(self, output_path: Optional[str] = None) -> str:
        """
        Generate a Data Processing Agreement (DPA) template.
        
        Args:
            output_path (str, optional): Path to save the DPA document
            
        Returns:
            str: DPA content
        """
        dpa_content = self._create_dpa_content()
        
        if output_path:
            try:
                with open(output_path, 'w', encoding='utf-8') as f:
                    f.write(dpa_content)
                logger.info(f"Data Processing Agreement saved to: {output_path}")
            except Exception as e:
                logger.error(f"Error saving DPA: {e}")
        
        return dpa_content
    
    def _create_dpa_content(self) -> str:
        """Create the Data Processing Agreement content."""
        return f"""# Data Processing Agreement (DPA)
# MoM Generator Application

**Effective Date:** {datetime.now().strftime('%B %d, %Y')}
**Data Controller:** {self.organization_name}
**Data Processor:** MoM Generator Application

## 1. Definitions

For the purposes of this DPA:
- **"Personal Data"** means any information relating to an identified or identifiable natural person
- **"Processing"** means any operation performed on personal data
- **"Data Subject"** means the individual whose personal data is being processed

## 2. Subject Matter and Duration

### 2.1 Subject Matter
This DPA governs the processing of personal data through the MoM Generator application for the purpose of generating meeting minutes and related documentation.

### 2.2 Duration
This DPA remains in effect for as long as the MoM Generator processes personal data on behalf of the Data Controller.

## 3. Nature and Purpose of Processing

### 3.1 Nature of Processing
- Collection of meeting transcripts and audio recordings
- Analysis and extraction of meeting content
- Generation of structured meeting minutes
- Storage and retrieval of processed data

### 3.2 Purpose of Processing
- Creating structured meeting documentation
- Facilitating meeting follow-up and action tracking
- Providing searchable meeting archives

## 4. Categories of Data Subjects

- Meeting participants and attendees
- Speakers in recorded meetings
- Individuals mentioned in meeting discussions

## 5. Categories of Personal Data

- **Voice Data:** Audio recordings of meeting participants
- **Identification Data:** Names and roles of meeting participants
- **Communication Data:** Statements and discussions during meetings
- **Professional Data:** Work-related information shared during meetings

## 6. Technical and Organizational Measures

### 6.1 Data Security
- Encryption of data in transit and at rest
- Access controls and authentication mechanisms
- Regular security assessments and updates
- Secure data deletion procedures

### 6.2 Data Minimization
- Processing only data necessary for the specified purpose
- Automatic deletion based on retention policies
- Option for data anonymization

### 6.3 Privacy by Design
- Built-in privacy controls and settings
- Offline processing options
- User control over data sharing and retention

## 7. Data Subject Rights

The application provides mechanisms to facilitate:
- Access to personal data
- Rectification of inaccurate data
- Erasure of personal data
- Restriction of processing
- Data portability
- Objection to processing

## 8. Data Transfers

### 8.1 Local Processing
- Default operation processes data locally
- No international transfers in offline mode

### 8.2 Third-Party Services
- When using online features, data may be transferred to AI service providers
- All transfers are governed by appropriate safeguards
- Users can restrict processing to local-only mode

## 9. Subprocessors

### 9.1 Current Subprocessors
- AI Processing Services (when online mode is used)
- Integration Services (when enabled by user)

### 9.2 Subprocessor Requirements
- All subprocessors must provide adequate data protection guarantees
- Subprocessors are bound by data processing agreements
- Users are notified of any changes to subprocessors

## 10. Data Breach Notification

In the event of a personal data breach:
- The Data Controller will be notified within 72 hours
- Affected data subjects will be notified if required by law
- Appropriate measures will be taken to mitigate the breach

## 11. Compliance and Auditing

### 11.1 Compliance Monitoring
- Regular compliance assessments
- Documentation of processing activities
- Privacy impact assessments when required

### 11.2 Audit Rights
- The Data Controller may audit compliance with this DPA
- Technical and organizational measures are subject to review
- Audit findings will be addressed promptly

## 12. Data Deletion and Return

Upon termination of this agreement:
- All personal data will be securely deleted
- Data deletion will be confirmed in writing
- Backup copies will be securely destroyed

---

**Data Controller Signature:** _________________________
**Date:** _________________________

**Data Processor Representative:** MoM Generator Application
**Date:** {datetime.now().strftime('%B %d, %Y')}
"""
    
    def generate_compliance_checklist(self) -> Dict[str, Any]:
        """
        Generate a privacy compliance checklist.
        
        Returns:
            Dict[str, Any]: Compliance checklist
        """
        checklist = {
            'gdpr_compliance': {
                'lawful_basis': {
                    'status': 'compliant',
                    'details': 'Processing based on legitimate interest and user consent'
                },
                'data_minimization': {
                    'status': 'compliant',
                    'details': 'Only necessary data is processed'
                },
                'purpose_limitation': {
                    'status': 'compliant',
                    'details': 'Data used only for meeting documentation purposes'
                },
                'storage_limitation': {
                    'status': 'compliant' if self.config.get('auto_delete_transcripts', False) else 'needs_attention',
                    'details': 'Automatic deletion available but may need to be enabled'
                },
                'data_subject_rights': {
                    'status': 'compliant',
                    'details': 'All GDPR rights are supported through the application'
                }
            },
            'ccpa_compliance': {
                'right_to_know': {
                    'status': 'compliant',
                    'details': 'Privacy policy clearly describes data collection'
                },
                'right_to_delete': {
                    'status': 'compliant',
                    'details': 'Users can delete their data at any time'
                },
                'right_to_opt_out': {
                    'status': 'compliant',
                    'details': 'Offline mode allows complete opt-out of data sharing'
                }
            },
            'security_measures': {
                'encryption': {
                    'status': 'compliant',
                    'details': 'Data encrypted in transit and at rest'
                },
                'access_controls': {
                    'status': 'compliant',
                    'details': 'Strict access controls implemented'
                },
                'secure_deletion': {
                    'status': 'compliant',
                    'details': 'Multi-pass secure deletion available'
                }
            },
            'recommendations': self._generate_compliance_recommendations()
        }
        
        return checklist
    
    def _generate_compliance_recommendations(self) -> List[str]:
        """Generate compliance recommendations."""
        recommendations = []
        
        if not self.config.get('auto_delete_transcripts', False):
            recommendations.append("Enable automatic data deletion to ensure compliance with retention policies")
        
        if not self.config.get('privacy_mode', False):
            recommendations.append("Consider enabling privacy mode by default for enhanced compliance")
        
        if not self.config.get('anonymization_available', True):
            recommendations.append("Implement data anonymization features for better privacy protection")
        
        recommendations.extend([
            "Regularly review and update privacy policies",
            "Conduct periodic privacy impact assessments",
            "Provide privacy training for all users",
            "Maintain documentation of all data processing activities",
            "Implement privacy by design principles in all new features"
        ])
        
        return recommendations